---

- name: create tigerjython directory
  file:
    path: '/opt/tigerjython'
    state: directory

- name: download tigerjython2
  get_url:
    url: http://www.tjgroup.ch/download/tigerjython2.jar
    dest: '/opt/tigerjython/tigerjython2.jar'

- name: download tigerjython4kids docs
  get_url:
    url: 'http://www.tigerjython4kids.ch/download/{{ item }}'
    dest: '/opt/tigerjython/{{ item }}'
  with_items: '{{ docs }}'

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
